### ISSUE TITLE
Resume ongoing task after docking

### ISSUE THREAD

**Issue by sebastian3107** [mikey0000/Mammotion-HA#190]
### The problem

Is there a way to resume a task after the robot has been sent back to the dock?
I tried using the [general lawn mower](https://www.home-assistant.io/integrations/lawn_mower/) action like `lawn_mower.start_mowing` which should also handle the resume function. This fails with this notification in the Mammotion app when the robot is docked:
![image](https://github.com/user-attachments/assets/6afdc468-4464-4059-a85e-06dd5d61b047)
This resuming does work if the robot has only been paused previously via `lawn_mower.pause` and is not docked.

I am looking for a way to press this resume button via the integration.
![image](https://github.com/user-attachments/assets/c8144d76-26dd-49b5-b9b2-0b9cd917d41d)

Is there a plan to have an action like `mammotion.resume_mow`?

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

v0.1.78

### What version of Home Assistant Core are you running?

core-2024.10.3

**Comment by mikey0000** [comment]
Seems to be a similar issue as to what was raised in Discord, I'll check the resume logic and see whats going on.

**Comment by mikey0000** [comment]
I fixed this today, will be out in next release to verify

**Comment by mikey0000** [comment]
Please try 0.1.88

**Comment by mikey0000** [comment]
Reasonably sure this is solved now, feel free to reopen if its not.

**Comment by sebastian3107** [comment]
I just tried it with 0.1.91 and still get the "Mowing area selection is abnormal" when I try to resume a task while being docked.

**Comment by mikey0000** [comment]
> I just tried it with 0.1.91 and still get the "Mowing area selection is abnormal" when I try to resume a task while being docked.

This is resuming when the mower has gone to dock on its own right? What model do you have?

**Comment by sebastian3107** [comment]
> This is resuming when the mower has gone to dock on its own right?

That I haven't tested. What I meant is when I sent it to the dock either manually in the app or via the integration.

**Comment by mikey0000** [comment]
OK and that's during a mow? As I thought I'd tested this, this is easier to test as well. I'll retry it tomorrow.

**Comment by mikey0000** [comment]
OK I think I saw whats happening, I just had my mower randomly pause for no reason at all, and it was in mode_ready. Which will definitely throw HA off in terms of logic. Can you confirm the activity mode was mode_ready?

**Comment by sebastian3107** [comment]
![image](https://github.com/user-attachments/assets/2b2a2c37-72a2-4588-b608-6a8e0c31fe78)
It goes from MODE_RETURNING back to MODE_READY, despite still having a task active.

**Comment by mikey0000** [comment]
Cool now I know what's happening I can resolve it. Really annoying lying though

**Comment by mikey0000** [comment]
Can you try on the latest release please

**Comment by sebastian3107** [comment]
I tried using v0.1.100, but I still see the same error in the Mammotion app.

Steps to reproduce:
1. Start a task in the app (I haven't tried starting the task via the integration)
2. Send Luba back to dock using the house icon in HA.
3. Try to resume the task via the HA integration once the robot has docked.

**Comment by sebastian3107** [comment]
Sorry for the delay, but we already had some snow here last week.
I just tried it again using v0.1.107, but I still see the same behavior on Luba 1.
In the app I get the error code 1415 when I try to resume a task from the dock. 
It is sitting on the dock in the states MODE_READY and CHARGE_ON, but it still has the active work area hash (instead of "Not working").

**Comment by mikey0000** [comment]
> Sorry for the delay, but we already had some snow here last week. I just tried it again using v0.1.107, but I still see the same behavior on Luba 1. In the app I get the error code 1415 when I try to resume a task from the dock. It is sitting on the dock in the states MODE_READY and CHARGE_ON, but it still has the active work area hash (instead of "Not working").

OK I'll see if I can find out what's going on specifically for the Luba 1's

**Comment by jotel** [comment]
Hey @mikey0000 did you have a chance to look at it? Since Luba 1 lacks a feature not to mow at certain times (e.g. after dusk) it would be very useful to create an automation which will pause mowing at certain time (or on other conditions), send to dock and resume next day when a morning dew has already evaporated.

**Comment by mikey0000** [comment]
Not yet, been busy reworking the entire integration but I'll start looking into this

**Comment by sebastian3107** [comment]
I just tested it on v0.2.18 and I still see the same behavior when trying to resume an active task (Error 1415).

**Comment by mikey0000** [comment]
Diagnostic please, I've been trying to reproduce for a while now.

**Comment by sebastian3107** [comment]
Here is my diagnostic output. I removed some info about other HACS installs and the location data of the robot.

[config_entry-mammotion-01JAKEEDW5YVM00DS7JD9QJMK6.json](https://github.com/user-attachments/files/19599947/config_entry-mammotion-01JAKEEDW5YVM00DS7JD9QJMK6.json)

**Comment by mikey0000** [comment]
Awesome, this should give me some insight into what state the mower is reporting

**Comment by mikey0000** [comment]
please try v0.2.26

**Comment by Nusse469** [comment]
I'm on 2.26 and getting the same error with my Luba 1.

**Comment by mikey0000** [comment]
Hmm that's not how resume works... Though the L1 tends to do some things differently to the rest. There is something called a breakpoint and that is what I changed the integration to look at. Seems to fix newer models but break L1s?

**Comment by mikey0000** [comment]
Once your mower is in a paused state please get a diagnostic and post it here

**Comment by sebastian3107** [comment]
I have some new insights. I named all of the areas (which only had hashes as names) according to the name in the Mammotion app by starting a task for each of them using the integration and looking in the app which one got selected. For one of the areas (the largest and directly next to the dock) I got an error in the app (1417) that the selected task area is invalid. I changed one border ot that zone a while ago and it must have changed the hash somehow.
I tried the sync map button of the integration, but nothing changed.
There is also a clear map button. Does it delete the areas from the robot or is that only for the integration? I don't want to remap everything.

When starting a task in that area (via the app) the mode changes correctly to MODE_WORKING, but the task area (which shows the area hash for other zones) stays on "Not working".

For other zones pausing and resuming now works! 👍🏼 
But only when the robot is in the area. When it is sent back to the dock I still can't resume in any zone. When on the dock (or on the way to the dock) it also says "Not working" for the selected task area, so that might be related.

![Image](https://github.com/user-attachments/assets/a4aced6a-1ac3-41b6-8e5c-564b49864a34)
![Image](https://github.com/user-attachments/assets/ac596691-1d50-458f-b76f-4a377fbe6b5a)
![Image](https://github.com/user-attachments/assets/cffc54e7-c6ed-43ac-8aa4-3fd21a60adc1)

**Comment by mikey0000** [comment]
clear maps is only on Home Assistant, so it safe to clear, to resume a mow all you need to do is hit the resume button, it will resume whatever job it is currently doing.

**Comment by mikey0000** [comment]
with the invalid task area please post your diagnostic when it occurs, thanks

**Comment by Vinzoh** [comment]
Hello,
I have the same issue with Luba2 AWD. 
I am able to launch the job when I toggle an area and chose "start mowing". However, when it comes back automatically to the dock, the Resume Work button does not function. 

I have an issue I am trying to resolve with this integration, my mower can no longer charge above 40%. So I would like to tell it to resume mowing when battery reaches 37% charge. 

Thanks for all the work on this integration !

[config_entry-mammotion-01JSSJT819363E7H13VF2PNWSP.json](https://github.com/user-attachments/files/19954886/config_entry-mammotion-01JSSJT819363E7H13VF2PNWSP.json)

**Comment by mikey0000** [comment]
> Hello, I have the same issue with Luba2 AWD. I am able to launch the job when I toggle an area and chose "start mowing". However, when it comes back automatically to the dock, the Resume Work button does not function.
> 
> I have an issue I am trying to resolve with this integration, my mower can no longer charge above 40%. So I would like to tell it to resume mowing when battery reaches 37% charge.
> 
> Thanks for all the work on this integration !
> 
> [config_entry-mammotion-01JSSJT819363E7H13VF2PNWSP.json](https://github.com/user-attachments/files/19954886/config_entry-mammotion-01JSSJT819363E7H13VF2PNWSP.json)

What version are you on?

**Comment by mikey0000** [comment]
Just pushed out a new version, give it a go

**Comment by mikey0000** [comment]
> It works !!
> Thanks!
> […](#)

Thanks for uploading your diagnostic so I could see what was going on.

**Comment by ellzzett** [comment]
Hi,

I'm not sure if the initial issue has been resolved or not.

I'm still experiencing a problem when the robot returns to the docking station during mowing because the battery drops below 15%. Normally, it should resume mowing once the battery reaches 80%, but this doesn't happen.

The docking station is not located directly within a mowing zone, but is connected via a channel.

Would it be possible to solve this using an automation? For example: check if the battery level is above 80% and the mowing progress is greater than 0 but less than 100 — then continue mowing.
If so, which entity should I use to implement such logic?

Thanks in advance!

**Comment by mikey0000** [comment]
Just use the lawn_mower.start_mowing action this will resume, battery stats are already reportex

**Comment by mikey0000** [comment]
> Hey [@mikey0000](https://github.com/mikey0000) , I think the behaviour improved a lot, I can pause/resume while my Luba 1 is mowing, but once I send it to the dock, there is no way to resume currently active mowing task.

You press the mow button to resume

**Comment by jotel** [comment]
> You press the mow button to resume

It does not trigger any action on the mower.  here is the card with "paused" task when mower returned to docking station 

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/f3c515d1-84dc-4fec-8c07-36245d52938b" />

and here some other  sensors:

<img width="278" alt="Image" src="https://github.com/user-attachments/assets/ab5a8c74-0e28-443a-9c51-52e017461048" />

I have  diagnostic and debug logs after the mow button was pressed, but I don't feel comfortable sharing them publicly here.
