### ISSUE TITLE
error on haos beta Version 2025.3

### ISSUE THREAD

**Issue by user86000** [mikey0000/Mammotion-HA#225]
### The problem

Unable to install package pymammotion==0.3.8: × No solution found when resolving dependencies: ╰─▶ Because pymammotion==0.3.8 depends on paho-mqtt>=1.6.1,<2.0.0 and paho-mqtt==2.1.0, we can conclude that pymammotion==0.3.8 cannot be used. And because you require pymammotion==0.3.8, we can conclude that your requirements are unsatisfiable.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.110

### What version of Home Assistant Core are you running?

2025.3.0b0

**Comment by mikey0000** [comment]
Yup aware of this one, thanks for raising though. I've already got a fix in a newer version of the library but I'm aiming to have a new release out before the first wednesday of March.

**Comment by mikey0000** [comment]
@user86000 give v0.2.0beta1 a try. Lots of changes, lots of rework done which should make it a lot better and future improvements.

**Comment by mikey0000** [comment]
@user86000 couple issues found, I've released 0.2.0-beta3 but if you want to test with the beta of Home Assistant just change the pymammotion version back 1 beta e.g it will be b2 change it back to b1

**Comment by jdominiczak** [comment]
Any Update on a release that will work with 2025.03?  I'm still getting the error on v0.2.0-beta7

**Comment by mikey0000** [comment]
Yeah I'll have a release out today, just needed some testing done on older versions

**Comment by mikey0000** [comment]
https://github.com/mikey0000/Mammotion-HA/releases/tag/v0.2.0-beta10
