### ISSUE TITLE
Commands Not Working on Luba2 3000X

### ISSUE THREAD

**Issue by ngm47** [mikey0000/Mammotion-HA#241]
### The problem

Hello,
I’m experiencing an issue with the Luba2 3000X where the commands are not executing as expected. Despite this, the data is being reported correctly, and I am able to retrieve information without any issues.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.2.4

### What version of Home Assistant Core are you running?

core-2025.3.2

**Comment by roninf** [comment]
I have got issues that might be similar, i can dock off the robot using the integration but i won`t go back in afterwards and i recognized that the status of the robot is still shown as docked in while its not. Maybe this is related, it seems that the status is not updated.

**Comment by mikey0000** [comment]
Which commands? I have a Luba 2 and have never encountered this.

Reproduction steps please.

**Comment by ngm47** [comment]
Good evening, here is the log, I sent the "mow" command twice.

[home-assistant_mammotion_2025-03-14T20-05-52.059Z.log](https://github.com/user-attachments/files/19254012/home-assistant_mammotion_2025-03-14T20-05-52.059Z.log)

**Comment by mikey0000** [comment]
Did you have a zone / area switch on?

**Comment by ngm47** [comment]
Yes, « Zone Nord »

**Comment by mikey0000** [comment]
OK I can see the sent command I'll decode it and take a look later on today (Saturday for me got house work to do) and work out what's happened. Can you also screenshot all the options when setting up a standard mow on the 3000X from the app just in case it's different from the Luba 2 non X

**Comment by ngm47** [comment]
![Image](https://github.com/user-attachments/assets/16f5ac67-f4fe-473a-aa66-aa03b29a6d6a)

This page?

**Comment by mikey0000** [comment]
Yes, any chance in English? Otherwise I'll use Google translate

**Comment by ngm47** [comment]
![Image](https://github.com/user-attachments/assets/63f92cf6-75c9-4fd8-8b23-5468d2dea422)

**Comment by mikey0000** [comment]
Hey I've just pushed out a new version that might address the issue, if you could give it a shot and report back 0.2.5

**Comment by ngm47** [comment]
Hello, unfortunately it's still the same. Here is the log. Would you like me to give you access to my home assistant (it only runs for this plugin)? 

[home-assistant_mammotion_2025-03-18T08-19-03.869Z.txt](https://github.com/user-attachments/files/19311996/home-assistant_mammotion_2025-03-18T08-19-03.869Z.txt)

**Comment by mikey0000** [comment]
> Hello, unfortunately it's still the same. Here is the log. Would you like me to give you access to my home assistant (it only runs for this plugin)?
> 
> [home-assistant_mammotion_2025-03-18T08-19-03.869Z.txt](https://github.com/user-attachments/files/19311996/home-assistant_mammotion_2025-03-18T08-19-03.869Z.txt)

Yeah that would help me test faster. Do you have discord? Or otherwise you should be able to email me?

**Comment by ngm47** [comment]
mail

**Comment by mikey0000** [comment]
Sorted on 0.2.7
