### ISSUE TITLE
Luba 2 does not respont to commands

### ISSUE THREAD

**Issue by JanKruemmel** [mikey0000/Mammotion-HA#28]
Hello, first of all very nice that the integration is available and thanks for the time you are spending in dev.

My mower is connected and I can see all values like battery, status and so far.
But I can not statt / stop mowing. The mower does not respond to commends.

Any Suggestions?

All the best

Jan

**Comment by mikey0000** [comment]
Yeah we don't have Luba 2s so don't know why. I'll try and investigate.

**Comment by TTLucian** [comment]
Same problem here with Yuka robot.

**Comment by TTLucian** [comment]
Latest update doesn't fix the problem.

**Comment by mikey0000** [comment]
We are aware and are working on it, it requires pull all the map data off to issue the correct command, hold tight

**Comment by mikey0000** [comment]
Closing as it is now resolved.

**Comment by TTLucian** [comment]
The issue is still present on v0.0.22 for Yuka. Start command does nothing. Sync maps throws an error. All configuration switches and sliders are throwing errors.

**Comment by TTLucian** [comment]
Also, after start mowing in HA, Mammotion app shows error "Mowing area selection is abnormal (1415)". Am I missing something?
