### ISSUE TITLE
Region problem

### ISSUE THREAD

**Issue by GitKiller-HA** [mikey0000/Mammotion-HA#284]
### The problem

Connection timeout to host https://api.link.aliyun.com/living/account/region/get

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

latest

### What version of Home Assistant Core are you running?

.

**Comment by mikey0000** [comment]
This isn't something I can fix. I'll see about storing regions, but that's a lot of extra work when this only happens occasionally for a very small number of users and usually resolves itself.

Does the app if you log out and log back in still work? Or does it fail with the same error.

**Comment by GitKiller-HA** [comment]
It doesn't work :( I can't connect. I don't now how to fix regions, because there is no option in Mammotion app.

**Comment by mikey0000** [comment]
Something on your network might be blocking that url / China. If you can't login to the app as well.

**Comment by GitKiller-HA** [comment]
After upgrade mammtion robot app works fine.
How can I check if something is blocking ?

sob., 19 kwi 2025 o 21:49 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
You've made the secondary login? And you can login with that secondary account on tge mammotion app.

**Comment by GitKiller-HA** [comment]
No, I have one account. After upgrading the firmware robot everything works
fine with mammotion app. My home assistant discover mammotion robot, but i
can't configure it - error You know.

sob., 19 kwi 2025 o 22:00 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
Please follow the instructions and create a second account and share your mower to it, use the second account only with Home Assistant.

**Comment by GitKiller-HA** [comment]
Ok, I wil try

Thank You very much!

sob., 19 kwi 2025 o 22:06 Michael Arthur ***@***.***>
napisał(a):

**Comment by GitKiller-HA** [comment]
Hi,

I checked everything (I hope) and it seems that HA is blocking the
connection :( I don't know why I how ? May be there is some problem with
route from docker IP to LAN IP ?
Have you heard about that problem ? or any advice ?

Thank You very much.

Best regards,
Grzegorz

sob., 19 kwi 2025 o 22:06 Michael Arthur ***@***.***>
napisał(a):

**Comment by GitKiller-HA** [comment]
I have intel nuc i5 HAOS (
https://www.home-assistant.io/installation/generic-x86-64).
[image: image.png]

I have two integrations (this time) that I can't run because of
connection issues. AQUA TEMP and MAMMOTION. Both of them try to connect to
https://cloud.linked-go.com:449/crmservice/api (Aqua Temp)  and
https://api.link.aliyun.com/living/account/region/get (Mammotion).
If I will try to connect directly from router (UDM PRO): curl -s -H
"Content-Type: application/json; charset=utf-8" -X POST -d
'{"user_name":"gr****@***.com","password":"****","type":"2"}'
https://cloud.linked-go.com:449/crmservice/api/app/user/login.json there is
no problem, but from HA it doesn't connect. HA is connected directly to UDM
PRO via lan. Ping from HA to domain cloud.linked-go.com:449 and
api.link.aliyun.com are OK.
Telnet form UDM PRO to domain on 443 ports are OK.



wt., 22 kwi 2025 o 21:40 Michael Arthur ***@***.***>
napisał(a):

**Comment by GitKiller-HA** [comment]
I'am from Poland

śr., 23 kwi 2025 o 23:07 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
Hey I've just pushed a library version that has a fallback for regions, can you try it?
v0.4.24 just need to update the manifest library version

**Comment by mikey0000** [comment]
actually make that version 0.4.25 had to add poland

**Comment by GitKiller-HA** [comment]
There is no 0.4.25 I've tried three version 0.2.24, 0.2.25, 0.2.26 white no
luck :( the same error

śr., 23 kwi 2025 o 23:34 Michael Arthur ***@***.***>
napisał(a):

**Comment by GitKiller-HA** [comment]
Could you send me full: curl for this api https://api.link.aliyun.com/living/account/region/get I will try to check if goes directly from router then ha

**Comment by mikey0000** [comment]
update pymammotion to 0.4.25

**Comment by mikey0000** [comment]
as for the curl, curl -X POST https://api.link.aliyun.com/living/account/region/get -vvv
that should return a header error

**Comment by GitKiller-HA** [comment]
Znalazłem :) Z jakiegoś powodu biego IPv6 :(

czw., 24 kwi 2025 o 01:06 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
Well that's OK, home assistant should be able to handle that.

**Comment by mikey0000** [comment]
when I hit it, its ipv4, which indicates a DNS issue.

**Comment by GitKiller-HA** [comment]
[image: image.png]

czw., 24 kwi 2025 o 01:14 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
OK should be resolved in pymammotion 0.4.26 which is being published now. Can you update pymammotion in the integration please. You'll need to edit the manifest file.

**Comment by GitKiller-HA** [comment]
I updated manifest restart i still no luck

[image: image.png]

czw., 24 kwi 2025 o 01:23 Michael Arthur ***@***.***>
napisał(a):

**Comment by GitKiller-HA** [comment]
May be there is problem with certificate ?

czw., 24 kwi 2025 o 01:23 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
don't know please update to 0.2.27 should be sorted

**Comment by mikey0000** [comment]
the images aren't being uploaded btw, if you have an issue with 0.2.27 please post logs

**Comment by GitKiller-HA** [comment]
Error setting up entry *******l.com for mammotion: Connection timeout to
host https://api.link.aliyun.com/living/account/region/get
Traceback (most recent call last):
  File "/config/custom_components/mammotion/__init__.py", line 99, in
async_setup_entry
    await mammotion.login_and_initiate_cloud(account, password)
  File
"/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion.py",
line 187, in login_and_initiate_cloud
    cloud_client = await self.login(account, password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion.py",
line 258, in login
    await self.connect_iot(mammotion_http, cloud_client)
  File
"/usr/local/lib/python3.13/site-packages/pymammotion/mammotion/devices/mammotion.py",
line 266, in connect_iot
    await cloud_client.get_region(country_code,
mammotion_http.login_info.authorization_code)
  File
"/usr/local/lib/python3.13/site-packages/pymammotion/aliyun/cloud_gateway.py",
line 183, in get_region
    response = await client.async_do_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        "/living/account/region/get", "https", "POST", None, body,
RuntimeOptions()

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File
"/usr/local/lib/python3.13/site-packages/pymammotion/aliyun/client.py",
line 222, in async_do_request
    raise UnretryableException(_last_request, _last_exception)
Tea.exceptions.UnretryableException: Connection timeout to host
https://api.link.aliyun.com/living/account/region/get

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 751,
in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 113, in
async_setup_entry
    raise ConfigEntryError(err)
homeassistant.exceptions.ConfigEntryError: Connection timeout to host
https://api.link.aliyun.com/living/account/region/get

czw., 24 kwi 2025 o 02:00 Michael Arthur ***@***.***>
napisał(a):

**Comment by mikey0000** [comment]
OK I guess I'll keep investigating, I set it to ipv4 only so it should be able to reach it. Can you try curl with - ipv4 from home assistant?

**Comment by GitKiller-HA** [comment]
curl -4 -X POST https://api.link.aliyun.com/living/account/region/get -vvv

I have two instances of HA in different locations:
Difference is on SSL (last line) ossl_bio_cf_in_read(len=5)  -> 5 vs
ossl_bio_cf_in_read(len=5)  -> -1
I don't know if it's important

Here works:
[image: image.png]

Here not:

[image: image.png]

czw., 24 kwi 2025 o 02:24 Michael Arthur ***@***.***>
napisał(a):

**Comment by jcraigc6** [comment]
I came here to report the same, but the above conversation resolved it. I had China geo-blocked in my Unifi setup. Removed the block and everything worked. I don't love pulling the block but can deal with that later. Thanks, guys!

**Comment by GitKiller-HA** [comment]
Could you tell me where exactly this lock is? I suspected the same thing,
but I looked through the settings and found nothing.

czw., 24 kwi 2025 o 05:03 jcraigc6 ***@***.***> napisał(a):

**Comment by MacValley** [comment]
Thanks for the hint that Unifi could be the "blocker". It definitely was for me! In my Unifi network settings for Region Blocking China was blocked. I deleted China, and then reconfigured the integration in Home Assistant and, yes, now I could see all entities, controls etc. I then blocked China again and the integration still worked. Time will show if I have to unblock China later on if firmware changes things? But for now it works.

**Comment by GitKiller-HA** [comment]
Could you show (print screen) Where unifi had this settings ? Did you
configure this setting yourself or unifi did this automaticly ?

W dniu pt., 25 kwi 2025 o 18:20 MacValley ***@***.***>
napisał(a):

**Comment by jcraigc6** [comment]
Glad this helped. For Unifi geo-blocking:

Network Console -> Settings -> Security -> Click Protection tab at top -> Region Blocking

I had added China along with a number of other countries. Unifi did not do this by default

**Comment by GitKiller-HA** [comment]
Ok, I don’t have set up any region to block so in my case it is not this
problem.

W dniu pt., 25 kwi 2025 o 18:52 jcraigc6 ***@***.***>
napisał(a):

**Comment by MacValley** [comment]
Just a quick reflection to GitKiller-HA: If you don't have Unifi, is there a possibility that the address is blocked in other ways? Some other firewall, router or perhaps you have PiHole? Came to think about PiHole because I had another issue (not at all related to Home Assistant) where I could whitelist a particular address to make things work. 
And to clarify: China was blocked in Unifi by me (Region Blocking is disabled by default I think).

**Comment by GitKiller-HA** [comment]
I have unifi udm pro and from bash in can connect to api (ciel) but from ha
I can’t. I have nuc with haos.

W dniu pt., 25 kwi 2025 o 19:55 MacValley ***@***.***>
napisał(a):

**Comment by nilsella** [comment]
> I came here to report the same, but the above conversation resolved it. I had China geo-blocked in my Unifi setup. Removed the block and everything worked. I don't love pulling the block but can deal with that later. Thanks, guys!

That was my problem as well. Thank you for this hint!

**Comment by mikey0000** [comment]
> I have unifi udm pro and from bash in can connect to api (curl) but from ha
> I can’t. I have nuc with haos.

Any chance you've managed to solve the issue?

**Comment by kristofgoethals** [comment]
![Image](https://github.com/user-attachments/assets/23546368-2fca-4229-8bdd-2f400a2a139d)

where to find in unifi , i had the same error

**Comment by GitKiller-HA** [comment]
Hi,

I think it is the issue UDM Pro. UDM Pro block some connections silently (for example XBOX Gta online). \
And quastion: which port should be open/forward fot this integration ? I'll try to forward ports may be this helps ?
